theme = "awesome-identity"
baseURL = "https://filipealex.github.io/"
title = "Fiipe Barroso - Software Engineer · Database Administrator"
languageCode = "en-US"
# Content without language indicator will default to this language
defaultContentLanguage = "en"
# Make .Summary and .WordCount behave correctly for CJK languages
hasCJKLanguage = true
PygmentsCodeFences = true
# Enable to turn relative URLs into absolute
canonifyURLs = true
# Do not convert the url/path to lowercase
disablePathToLower = false
# Enable Emoji emoticons support for page content
enableEmoji = true
# Update the `Lastmod` parameter for each page using the last git commit date for that content file
enableGitInfo = true
# Enable generation of `robots.txt` file
enableRobotsTXT = true

# Google Analytics tracking ID
googleAnalytics = "UA-153439313-1"


# Add your own params here
[params]
  # Google Webmaster
  # https://www.google.com/webmasters/
  # googleSiteVerification = ""

## Meta Configurations (HTTP Meta tags & OpenGraph)
[params.meta]
  description = "Fiipe Barroso - Software Engineer · Database Administrator"
  keywords = "filipe, barroso, alex, software, dba, database, administration, backend, engineer, developer"
  images = [
    "/images/profile.jpg"
  ]


## Profile Configurations
[params.profile]
  portrait = "/images/profile.jpg"
  firstname = "Filipe"
  lastname = "Barroso"
  title = "Software Engineer · Database Administrator"
  bio = """A self-motivated software developer professional with the ability to grasp new concepts, understand complex ideas and continually master new skills. 
  
  Experienced in database administration and back-end software development. 
  Applies rigour and creativity by combining expertise in programming languages, database development and computer science to solve diverse enterprise application problems. 
  
  Ability to work well on a team and individually."""

## Contacts Configurations
[params.contacts]
  email = "filipe.alex.barroso@gmail.com"
  github = "FilipeAlex"
  linkedin = "filipe-alex-barroso"

## Actions Configurations
[[params.actions]]
  name = "Review My CV"
  url = "https://www.dropbox.com/s/y0zrw00g9nq1y93/Filipe-Barroso-CV.pdf?dl=0"


## Privacy Configurations (GDPR)
[privacy]
  [privacy.googleAnalytics]
    disable = false
    # Make the users’ IP addresses are anonymized within Google Analytics
    anonymizeIP = false
    # Make the GA templates respect the “Do Not Track” HTTP header
    respectDoNotTrack = false
    # Disable the use of Cookies and use Session Storage to Store the GA Client ID
    useSessionStorage = false
	
## Footer Configurations
[params.footer]
  copyright = "© 2019 Filipe Barroso. [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/)."
  poweredBy = true
